# Generated by Django 4.0.2 on 2022-03-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageName',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
