# Generated by Django 4.0.2 on 2022-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_remove_post_excerpt_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
